namespace BlastPDF.Internal.Structure;

public enum PdfObjectType
{
    // PDF OBJECT TYPES
    BOOLEAN, NUMERIC, NULL,
    LITERAL_STRING, HEX_STRING, NAME, 
    ARRAY, DICTIONARY, STREAM,
    INDIRECT_OBJ, INDIRECT_REF,
    
    // KIND OF OBJECTS
    STREAM_CONTENT, COMMENT,
    
    // PARSER MARKERS
    ARRAY_START, DICT_START,
    OBJ_START, STREAM_START,
    XREF_START,
    
    // FILE SECTIONS
    XREF_TABLE, XREF_SECTION, XREF_SUB_SECTION, XREF_ENTRY,
    TRAILER,
}