using Microsoft.CodeAnalysis;

namespace BlastPDF.Template;

[Generator]
public class TemplateGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var templates = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".bxpdf"))
            .Select(static (file, cancellationToken) => 
                (path: file.Path, name: Path.GetFileNameWithoutExtension(file.Path), content: file.GetText(cancellationToken)?.ToString() ?? ""));
        
        context.RegisterSourceOutput(templates, (spc, template) =>
        {
            var values = new Lexer(template.content).Aggregate("",
                (result, item) =>
                    result + $">>> '{item.Lexeme.Replace("\"", "\"\"")}' {item.Type} Line: {item.Line.Item1} Column: {item.Column.Item1}\n");

            var ast = Parser.Parse(template.content);

            var errors = ast.GetErrors(template.path).ToList();
            if (errors.Count != 0)
            {
                errors.ForEach(spc.ReportDiagnostic);
                return;
            }

            spc.AddSource($"BlastPDF.Template.{template.name}.g.cs", $@"// <auto-generated>
// This code was auto generated by BlastPDF.Template
using System;
using System.IO;
using BlastPDF.Builder;
using BlastPDF.Builder.Graphics;
using BlastPDF.Builder.Graphics.Drawing;
using BlastPDF.Filter;
using BlastPDF.Exporter.Basic;
{{importSource}}
{{namespaceSource}}
public class {template.name} : IPdfTemplate {{
{{variableSource}}
public void Save(Stream stream) {{
Console.WriteLine(""AST::::"");
{{documentNode.GenerateSource()}}.Save(stream);
}}}}");
        });
        
    }
}